name: Deploying Infrastructure using Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Add terraform.tfvars
        run: |
          cat << EOF > devops/tf/terraform.tfvars
          azure_client_id       = "${{ secrets.AZURE_CLIENT_ID }}"
          azure_client_secret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
          azure_tenant_id       = "${{ secrets.AZURE_TENAND_ID }}"
          azure_subscription_id = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          EOF
      - name: Terraform init
        run: terraform -chdir=devops/tf/ init
      - name: Terraform Format
        run: terraform -chdir=devops/tf/ fmt
      - name: Terraform Validate
        run: terraform -chdir=devops/tf/ validate
      - name: Terraform Apply
        run: terraform -chdir=devops/tf/ apply -auto-approve
